# Generated by Django 4.2.13 on 2024-06-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zodiacapp",
            "0003_remove_favoritemovie_genre_remove_favoritemovie_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationshipstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("Vienišas", "Vienišas"),
                    ("Įsipareigojęs", "Įsipareigojęs"),
                    ("Susižadėjęs", "Susižadėjęs"),
                    ("Vedęs", "Vedęs"),
                    ("Komplikuota", "Komplikuota"),
                ],
                default="Single",
                help_text="Relationship status",
                max_length=20,
            ),
        ),
    ]
