# Generated by Django 4.2.13 on 2024-06-03 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zodiacapp", "0004_alter_relationshipstatus_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together={("user", "friend")},
        ),
    ]
