# Generated by Django 4.2.13 on 2024-06-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zodiacapp", "0005_alter_friendship_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                default="default_profile_picture.png", upload_to="profile_pictures/"
            ),
        ),
    ]
