# Generated by Django 4.2.13 on 2024-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zodiacapp", "0006_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                default="images/default_profile_picture.png",
                upload_to="profile_pictures/",
            ),
        ),
    ]
