# Generated by Django 4.2.13 on 2024-06-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zodiacapp", "0007_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="zodiac",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="relationshipstatus",
            name="color",
            field=models.CharField(
                choices=[
                    ("red", "Raudona"),
                    ("green", "Žalia"),
                    ("blue", "Mėlyna"),
                    ("yellow", "Geltona"),
                ],
                default="blue",
                help_text="Color for display",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="relationshipstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("Vienišas", "Vienišas"),
                    ("Įsipareigojęs", "Įsipareigojęs"),
                    ("Susižadėjęs", "Susižadėjęs"),
                    ("Vedęs", "Vedęs"),
                    ("Komplikuota", "Komplikuota"),
                ],
                default="Vienišas",
                help_text="Relationship status",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Friendship",
        ),
    ]
